name = "cloudflare-mini-chat"
pages_build_output_dir = "./public"
compatibility_date = "2024-11-01" 
type = "module" 

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"
script_name = "cloudflare-mini-chat"
